-- =====================================================
-- Reports & Data Analysis
-- =====================================================



-- Q1
-- Total Transaction Revenue by City
-- Identify which cities generate the highest transaction revenue.

SELECT 
    c.city,
    SUM(t.amount) AS total_revenue
FROM transactions t
JOIN accounts a
    ON t.account_id = a.account_id
JOIN customers c
    ON a.customer_id = c.customer_id
GROUP BY c.city
ORDER BY total_revenue DESC;



-- Q2
-- Number of Transactions per Customer
-- Identify customers with the highest number of transactions.

SELECT 
    a.customer_id,
    COUNT(t.transaction_id) AS transaction_count
FROM accounts a
JOIN transactions t
    ON a.account_id = t.account_id
GROUP BY a.customer_id
ORDER BY transaction_count DESC;



-- Q3
-- Maximum Transaction Amount by Each Customer

SELECT 
    a.customer_id,
    MAX(t.amount) AS max_transaction
FROM accounts a
LEFT JOIN transactions t
    ON a.account_id = t.account_id
GROUP BY a.customer_id;



-- Q4
-- Top Spending Customer in Each City

WITH customer_spending AS
(
SELECT 
    c.city,
    c.customer_id,
    SUM(t.amount) AS total_spent
FROM customers c
JOIN accounts a
    ON c.customer_id = a.customer_id
JOIN transactions t
    ON a.account_id = t.account_id
GROUP BY c.city,c.customer_id
)

SELECT *
FROM
(
SELECT 
    city,
    customer_id,
    total_spent,
    DENSE_RANK() OVER(
        PARTITION BY city
        ORDER BY total_spent DESC
    ) AS rnk
FROM customer_spending
) ranked
WHERE rnk = 1;



-- Q5
-- Customers Spending Above Platform Average

SELECT 
    a.customer_id,
    SUM(t.amount) AS total_spent
FROM accounts a
JOIN transactions t
    ON a.account_id = t.account_id
GROUP BY a.customer_id
HAVING SUM(t.amount) >
(
SELECT AVG(amount)
FROM transactions
);



-- Q6
-- Revenue Generated by Each Merchant Category

SELECT 
    m.category,
    SUM(t.amount) AS category_revenue
FROM merchants m
JOIN transactions t
    ON m.merchant_id = t.merchant_id
GROUP BY m.category
ORDER BY category_revenue DESC;



-- Q7
-- Top Merchant in Each Category

WITH merchant_revenue AS
(
SELECT 
    m.category,
    m.merchant_name,
    SUM(t.amount) AS total_revenue
FROM merchants m
JOIN transactions t
    ON m.merchant_id = t.merchant_id
GROUP BY m.category,m.merchant_name
)

SELECT *
FROM
(
SELECT *,
    DENSE_RANK() OVER(
        PARTITION BY category
        ORDER BY total_revenue DESC
    ) AS rnk
FROM merchant_revenue
) ranked
WHERE rnk = 1;



-- Q8
-- Daily Highest Spending Customer

WITH daily_spend AS
(
SELECT 
    c.customer_id,
    t.transaction_date,
    SUM(t.amount) AS total_spent
FROM transactions t
JOIN accounts a
    ON t.account_id = a.account_id
JOIN customers c
    ON a.customer_id = c.customer_id
GROUP BY c.customer_id,t.transaction_date
)

SELECT *
FROM
(
SELECT *,
    DENSE_RANK() OVER(
        PARTITION BY transaction_date
        ORDER BY total_spent DESC
    ) AS rnk
FROM daily_spend
) ranked
WHERE rnk = 1;



-- Q9
-- Customers Spending Above Their City Average

WITH city_customer_spend AS
(
SELECT 
    c.city,
    c.customer_id,
    SUM(t.amount) AS total_spent
FROM customers c
JOIN accounts a
    ON c.customer_id = a.customer_id
JOIN transactions t
    ON a.account_id = t.account_id
GROUP BY c.city,c.customer_id
)

SELECT *
FROM city_customer_spend cs
WHERE total_spent >
(
SELECT AVG(total_spent)
FROM city_customer_spend
WHERE city = cs.city
);



-- Q10
-- Top 2 Customers by Spending in Each City

WITH customer_spend AS
(
SELECT 
    c.city,
    c.customer_id,
    SUM(t.amount) AS total_spent
FROM customers c
JOIN accounts a
    ON c.customer_id = a.customer_id
JOIN transactions t
    ON a.account_id = t.account_id
GROUP BY c.city,c.customer_id
)

SELECT *
FROM
(
SELECT *,
    DENSE_RANK() OVER(
        PARTITION BY city
        ORDER BY total_spent DESC
    ) AS rnk
FROM customer_spend
) ranked
WHERE rnk <= 2;
