-- =====================================================
-- Reports & Data Analysis
-- =====================================================



-- Q1
-- Top Spending Customer in Each City
-- Identify the highest spending customer in every city based on total transaction amount.

WITH customer_spend AS
(
SELECT 
    c.city,
    c.customer_id,
    SUM(t.amount) AS total_spent
FROM customers c
JOIN accounts a
    ON c.customer_id = a.customer_id
JOIN transactions t
    ON a.account_id = t.account_id
GROUP BY c.city,c.customer_id
)

SELECT *
FROM
(
SELECT *,
    DENSE_RANK() OVER(
        PARTITION BY city
        ORDER BY total_spent DESC
    ) AS rank
FROM customer_spend
) ranked
WHERE rank = 1;



-- Q2
-- Customers Spending Above Their City Average
-- Identify customers whose total spending is greater than the average spending of customers in their city.

WITH city_customer_spend AS
(
SELECT 
    c.city,
    c.customer_id,
    SUM(t.amount) AS total_spent
FROM customers c
JOIN accounts a
    ON c.customer_id = a.customer_id
JOIN transactions t
    ON a.account_id = t.account_id
GROUP BY c.city,c.customer_id
)

SELECT *
FROM city_customer_spend cs
WHERE total_spent >
(
SELECT AVG(total_spent)
FROM city_customer_spend
WHERE city = cs.city
);



-- Q3
-- Top Merchant in Each Category
-- Identify the merchant generating the highest transaction revenue within each merchant category.

WITH merchant_revenue AS
(
SELECT 
    m.category,
    m.merchant_name,
    SUM(t.amount) AS total_revenue
FROM merchants m
JOIN transactions t
    ON m.merchant_id = t.merchant_id
GROUP BY m.category,m.merchant_name
)

SELECT *
FROM
(
SELECT *,
    DENSE_RANK() OVER(
        PARTITION BY category
        ORDER BY total_revenue DESC
    ) AS rank
FROM merchant_revenue
) ranked
WHERE rank = 1;



-- Q4
-- Daily Transaction Leaders
-- Identify the customer generating the highest transaction amount on each day.

WITH daily_spend AS
(
SELECT 
    c.customer_id,
    t.transaction_date,
    SUM(t.amount) AS total_spent
FROM transactions t
JOIN accounts a
    ON t.account_id = a.account_id
JOIN customers c
    ON a.customer_id = c.customer_id
GROUP BY c.customer_id,t.transaction_date
)

SELECT *
FROM
(
SELECT *,
    DENSE_RANK() OVER(
        PARTITION BY transaction_date
        ORDER BY total_spent DESC
    ) AS rank
FROM daily_spend
) ranked
WHERE rank = 1;



-- Q5
-- Top 2 Customers by Spending in Each City
-- Identify the top 2 highest spending customers in every city.

WITH customer_spend AS
(
SELECT 
    c.city,
    c.customer_id,
    SUM(t.amount) AS total_spent
FROM customers c
JOIN accounts a
    ON c.customer_id = a.customer_id
JOIN transactions t
    ON a.account_id = t.account_id
GROUP BY c.city,c.customer_id
)

SELECT *
FROM
(
SELECT *,
    DENSE_RANK() OVER(
        PARTITION BY city
        ORDER BY total_spent DESC
    ) AS rank
FROM customer_spend
) ranked
WHERE rank <= 2;



-- Q6
-- Merchant Category Revenue Contribution
-- Calculate total revenue generated by each merchant category and rank categories by revenue.

SELECT *
FROM
(
SELECT 
    m.category,
    SUM(t.amount) AS total_revenue,
    DENSE_RANK() OVER(
        ORDER BY SUM(t.amount) DESC
    ) AS rank
FROM merchants m
JOIN transactions t
    ON m.merchant_id = t.merchant_id
GROUP BY m.category
) ranked;



-- Q7
-- Cities with Highest Average Customer Spending
-- Identify cities with the highest average customer transaction spending.

WITH city_customer_spend AS
(
SELECT 
    c.city,
    c.customer_id,
    SUM(t.amount) AS total_spent
FROM customers c
JOIN accounts a
    ON c.customer_id = a.customer_id
JOIN transactions t
    ON a.account_id = t.account_id
GROUP BY c.city,c.customer_id
)

SELECT 
    city,
    AVG(total_spent) AS avg_customer_spend
FROM city_customer_spend
GROUP BY city
ORDER BY avg_customer_spend DESC;



-- Q8
-- Customers Without Loans but High Spending
-- Identify customers who have high transaction spending but do not currently have loans.

WITH customer_spend AS
(
SELECT 
    c.customer_id,
    SUM(t.amount) AS total_spent
FROM customers c
JOIN accounts a
    ON c.customer_id = a.customer_id
JOIN transactions t
    ON a.account_id = t.account_id
GROUP BY c.customer_id
)

SELECT *
FROM customer_spend cs
LEFT JOIN loans l
    ON cs.customer_id = l.customer_id
WHERE l.loan_id IS NULL
ORDER BY total_spent DESC;



-- Q9
-- Monthly Transaction Growth (MoM)
-- Calculate month-over-month growth in total transaction revenue.

WITH monthly_revenue AS
(
SELECT 
    MONTH(transaction_date) AS month,
    SUM(amount) AS revenue
FROM transactions
GROUP BY MONTH(transaction_date)
)

SELECT 
    month,
    revenue,
    LAG(revenue) OVER(ORDER BY month) AS previous_month,
    ROUND(
        (revenue - LAG(revenue) OVER(ORDER BY month)) /
        LAG(revenue) OVER(ORDER BY month) * 100
        ,2
    ) AS growth_percent
FROM monthly_revenue;



-- Q10
-- Customer Spending Rank Within Each City
-- Rank all customers within their city based on total transaction spending.

WITH customer_spend AS
(
SELECT 
    c.city,
    c.customer_id,
    SUM(t.amount) AS total_spent
FROM customers c
JOIN accounts a
    ON c.customer_id = a.customer_id
JOIN transactions t
    ON a.account_id = t.account_id
GROUP BY c.city,c.customer_id
)

SELECT 
    city,
    customer_id,
    total_spent,
    DENSE_RANK() OVER(
        PARTITION BY city
        ORDER BY total_spent DESC
    ) AS rank
FROM customer_spend;
